### ISSUE TITLE
is there any news on this plugin?

### ISSUE THREAD

**Issue by Ravenclawer** [pulsovi/obsidian-note-aliases#1]
adding the [[note|alias]] form of an alias to the YAML area of the note is one of the obsidian missing features. this plugin fills the gap, and could be a game changer when it released.

**Comment by pulsovi** [comment]
Hi,

Here is finally the first published release, thanks to your encouragement.

**Comment by Ravenclawer** [comment]
Thank you so much for publishing this plugin，I will try this plugin immediately

**Comment by Ravenclawer** [comment]
it works like a charm，thank you for this wonderful plugin

**Comment by Ravenclawer** [comment]
https://forum.obsidian.md/t/plugin-showcase-quickly-add-the-link-display-text-to-the-front-matter-of-the-target-note/52932?u=ocarinalover
I wrote a post on obsidian forum to introduce this amazing plugin
