### ISSUE TITLE
Great plugin, couple of suggestions from a first impression.

### ISSUE THREAD

**Issue by kerbless** [pulsovi/obsidian-note-aliases#2]
Works great and I love it, I have a couple of suggestions:

- Allow to change the syntax of the added alias (I use "alias:" with commas and I like it more than "aliases:" with dashes)
- Display a pop-up message if the alias is added successfully

Thanks you for your work!

**Comment by pulsovi** [comment]
Hello, 
Thank you for your appreciation.

The popup was added in the latest version (today).

The possibility of choosing the syntax used to record the aliases in YAML is currently too difficult to implement.

Indeed, I use the Obsidian API to modify the binary value (interpreted by the machine) of the "aliases" field, not its textual value in the .md file.

I hope that the API that Obsidian makes available to us will evolve to allow users to choose the syntax recorded in the file.

Add the management of the name version "alias" should be subject to a forthcoming bug correction.

**Comment by finn-matti** [comment]
A little late to the party, but: As a workaround you may be able to use [Obsidian Linter Plugin](https://github.com/platers/obsidian-linter): This can reformat your yaml frontmatter in the way you wish. It will still take some human intervention (like opening the nonte and using the command to lint and format the file), but it's better than nothing.
